apiVersion: v1
kind: Service
metadata:
  name: "{{ include "tn.name" . }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http
  selector:
    app: "{{ include "tn.name" . }}"
    # svc-meta-0: "stream-0"
    # svc-meta-1: "stream-1"
    # svc-meta-2: "stream-2"
    # svc-meta-3: "stream-3"
    # svc-meta-4: "stream-4"
    # svc-meta-5: "stream-5"
    # svc-meta-6: "stream-6"
    # svc-meta-7: "stream-7"
    # svc-meta-8: "stream-8"
    # svc-meta-9: "stream-9"
    # svc-meta-10: "stream-10"
    # svc-meta-11: "stream-11"
    # svc-meta-12: "stream-12"
    # svc-meta-13: "stream-13"
    # svc-meta-14: "stream-14"
    # svc-meta-15: "stream-15"
    # svc-meta-16: "stream-16"
    # svc-meta-17: "stream-17"
    # svc-meta-18: "stream-18"
    # svc-meta-19: "stream-19"
    # svc-meta-20: "stream-20"
    # svc-meta-21: "stream-21"
    # svc-meta-22: "stream-22"
    # svc-meta-23: "stream-23"
    # svc-meta-24: "stream-24"
    # svc-meta-25: "stream-25"
    # svc-meta-26: "stream-26"
    # svc-meta-27: "stream-27"
    # svc-meta-28: "stream-28"
    # svc-meta-29: "stream-29"
    # svc-meta-30: "stream-30"
    # svc-meta-31: "stream-31"
    # svc-meta-32: "stream-32"
    # svc-meta-33: "stream-33"
    # svc-meta-34: "stream-34"
    # svc-meta-35: "stream-35"
    # svc-meta-36: "stream-36"
    # svc-meta-37: "stream-37"
    # svc-meta-38: "stream-38"
    # svc-meta-39: "stream-39"
    # svc-meta-40: "stream-40"
    # svc-meta-41: "stream-41"
    # svc-meta-42: "stream-42"
    # svc-meta-43: "stream-43"
    # svc-meta-44: "stream-44"
    # svc-meta-45: "stream-45"
    # svc-meta-46: "stream-46"
    # svc-meta-47: "stream-47"
    # svc-meta-48: "stream-48"
    # svc-meta-49: "stream-49"
    # svc-meta-50: "stream-50"
    # svc-meta-51: "stream-51"
    # svc-meta-52: "stream-52"
    # svc-meta-53: "stream-53"
    # svc-meta-54: "stream-54"
    # svc-meta-55: "stream-55"
    # svc-meta-56: "stream-56"
    # svc-meta-57: "stream-57"
    # svc-meta-58: "stream-58"
    # svc-meta-59: "stream-59"
    # svc-meta-60: "stream-60"
    # svc-meta-61: "stream-61"
    # svc-meta-62: "stream-62"
    # svc-meta-63: "stream-63"
    # svc-meta-64: "stream-64"
    # svc-meta-65: "stream-65"
    # svc-meta-66: "stream-66"
    # svc-meta-67: "stream-67"
    # svc-meta-68: "stream-68"
    # svc-meta-69: "stream-69"
    # svc-meta-70: "stream-70"
    # svc-meta-71: "stream-71"
    # svc-meta-72: "stream-72"
    # svc-meta-73: "stream-73"
    # svc-meta-74: "stream-74"
    # svc-meta-75: "stream-75"
    # svc-meta-76: "stream-76"
    # svc-meta-77: "stream-77"
    # svc-meta-78: "stream-78"
    # svc-meta-79: "stream-79"
    # svc-meta-80: "stream-80"
    # svc-meta-81: "stream-81"
    # svc-meta-82: "stream-82"
    # svc-meta-83: "stream-83"
    # svc-meta-84: "stream-84"
    # svc-meta-85: "stream-85"
    # svc-meta-86: "stream-86"
    # svc-meta-87: "stream-87"
    # svc-meta-88: "stream-88"
    # svc-meta-89: "stream-89"
    # svc-meta-90: "stream-90"
    # svc-meta-91: "stream-91"
    # svc-meta-92: "stream-92"
    # svc-meta-93: "stream-93"
    # svc-meta-94: "stream-94"
    # svc-meta-95: "stream-95"
    # svc-meta-96: "stream-96"
    # svc-meta-97: "stream-97"
    # svc-meta-98: "stream-98"
    # svc-meta-99: "stream-99"
